In [100]:
import psycopg2
import pandas as pd
import numpy as np

In [2]:
def create_database():
    conn = psycopg2.connect("host=localhost user=postgres password=momdad23")
    conn.set_session(autocommit=True)
    cur=conn.cursor()

    return cur,conn

In [5]:
def drop_tables(cur,conn):
    for query in drop_table_queries:
        cur.execute(query)
        conn.commit()

In [7]:
def create_tables(cur,conn):
    for query in create_table_queries:
        cur.execute(query)
        conn.commit()

In [9]:
airlines = pd.read_csv("airlines.csv")

In [11]:
airlines.head()

,Airline ID,Name,Alias,IATA,ICAO,Callsign,Country,Active
0,-1,Unknown,\N,-,NaN,\N,\N,Y
1,1,Private flight,\N,-,NaN,NaN,NaN,Y
2,2,135 Airways,\N,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,\N,NaN,WYT,NaN,United Kingdom,N

In [135]:
airports = pd.read_csv("airports.csv")

In [137]:
airports.tail()

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database time zone,Type,Source
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.261200,-70.779198,670,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports

In [139]:
airports = airports[['Airport ID','Name','City','Country','IATA','ICAO','Altitude','Timezone','DST','Tz database time zone','Type','Source']]

In [149]:
airports['IATA'].replace([r'\N'],['None'],inplace=True)
airports['Tz database time zone'].replace([r'\N'],['None'],inplace=True)
airports['DST'].replace([r'\N'],['None'],inplace=True)
airports['Timezone'].replace(r'\N', 0, inplace=True)

In [151]:
airports.tail(10)

,Airport ID,Name,City,Country,IATA,ICAO,Altitude,Timezone,DST,Tz database time zone,Type,Source
7688,14101,Rustaq Airport,Al Masna'ah,Oman,MNH,OORQ,349,0,None,None,airport,OurAirports
7689,14102,Laguindingan Airport,Cagayan de Oro City,Philippines,CGY,RPMY,190,0,None,None,airport,OurAirports
7690,14103,Kostomuksha Airport,Kostomuksha,Russia,None,ULPM,681,0,None,None,airport,OurAirports
7691,14104,Privolzhskiy Air Base,Astrakhan,Russia,None,XRAP,-66,0,None,None,airport,OurAirports
7692,14105,Kubinka Air Base,Kubinka,Russia,None,UUMB,614,0,None,None,airport,OurAirports
7693,14106,Rogachyovo Air Base,Belaya,Russia,None,ULDA,272,0,None,None,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,None,XIUW,1670,0,None,None,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,None,ULLK,85,0,None,None,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,670,0,None,None,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,None,UKDM,0,0,None,None,airport,OurAirports

In [155]:
airports['IATA'].replace({None: np.nan})
airports['Tz database time zone'].replace({None: np.nan})
airports['DST'].replace({None: np.nan})

0          U
1          U
2          U
3          U
4          U
        ...
7693    None
7694    None
7695    None
7696    None
7697    None
Name: DST, Length: 7698, dtype: object

In [157]:
airports.tail(10)

,Airport ID,Name,City,Country,IATA,ICAO,Altitude,Timezone,DST,Tz database time zone,Type,Source
7688,14101,Rustaq Airport,Al Masna'ah,Oman,MNH,OORQ,349,0,None,None,airport,OurAirports
7689,14102,Laguindingan Airport,Cagayan de Oro City,Philippines,CGY,RPMY,190,0,None,None,airport,OurAirports
7690,14103,Kostomuksha Airport,Kostomuksha,Russia,None,ULPM,681,0,None,None,airport,OurAirports
7691,14104,Privolzhskiy Air Base,Astrakhan,Russia,None,XRAP,-66,0,None,None,airport,OurAirports
7692,14105,Kubinka Air Base,Kubinka,Russia,None,UUMB,614,0,None,None,airport,OurAirports
7693,14106,Rogachyovo Air Base,Belaya,Russia,None,ULDA,272,0,None,None,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,None,XIUW,1670,0,None,None,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,None,ULLK,85,0,None,None,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,670,0,None,None,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,None,UKDM,0,0,None,None,airport,OurAirports

In [19]:
airplanes = pd.read_csv("airplanes.csv")

In [21]:
airplanes.head()

                                           Name IATA code ICAO code
0                       Aerospatiale (Nord) 262       ND2      N262
1  Aerospatiale (Sud Aviation) Se.210 Caravelle       CRV      S210
2                  Aerospatiale SN.601 Corvette       NDC      S601
3                Aerospatiale/Alenia ATR 42-300       AT4      AT43
4                Aerospatiale/Alenia ATR 42-500       AT5      AT45

In [23]:
routes = pd.read_csv("routes.csv")

In [25]:
routes = routes[['Airline','Airline ID','Source airport','Source airport ID','Destination airport','Destination airport ID','Stops','Equipment']]

In [27]:
routes.head()

,Airline,Airline ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Stops,Equipment
0,2B,410,AER,2965,KZN,2990,0,CR2
1,2B,410,ASF,2966,KZN,2990,0,CR2
2,2B,410,ASF,2966,MRV,2962,0,CR2
3,2B,410,CEK,2968,KZN,2990,0,CR2
4,2B,410,CEK,2968,OVB,4078,0,CR2

In [181]:
routes.replace(r'\N', 0, inplace=True)

In [29]:
cur,conn = create_database()

In [31]:
airlines_table_create = ("""CREATE TABLE IF NOT EXISTS airlines(
Airline_ID INTEGER PRIMARY KEY,
Name VARCHAR,	
Alias VARCHAR,	
IATA VARCHAR,	
ICAO VARCHAR,	
Callsign VARCHAR,	
Country VARCHAR,	
Active VARCHAR
)""")

In [33]:
cur.execute(airlines_table_create)
conn.commit()

In [39]:
airports_table_create = ("""CREATE TABLE IF NOT EXISTS airports(
Airport_ID INTEGER PRIMARY KEY,
Name VARCHAR,	
City VARCHAR,
Country VARCHAR,
IATA VARCHAR,	
ICAO VARCHAR,	
Altitude INTEGER,	
Timezone INTEGER,	
DST VARCHAR,
Tz_database_time_zone VARCHAR,
Type VARCHAR,
Source VARCHAR
)""")

In [41]:
cur.execute(airports_table_create)
conn.commit()

In [43]:
airplanes_table_create = ("""CREATE TABLE IF NOT EXISTS airplanes(
Name VARCHAR,	
IATA_code VARCHAR,	
ICAO_code VARCHAR
)""")

In [45]:
cur.execute(airplanes_table_create)
conn.commit()

In [47]:
routes_table_create = ("""CREATE TABLE IF NOT EXISTS routes(
Airline VARCHAR,
Airline_ID INTEGER,
Source_airport VARCHAR,	
Source_airport_ID INTEGER,
Destination_airport VARCHAR,
Destination_airport_ID INTEGER,	
Stops INTEGER,	
Equipment VARCHAR
)""")

In [49]:
cur.execute(routes_table_create)
conn.commit()

In [72]:
airlines_table_insert = ("""INSERT into airlines(
Airline_ID,
Name,	
Alias,	
IATA,	
ICAO,	
Callsign,	
Country,	
Active)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
""")

In [74]:
for i, row in airlines.iterrows():
    cur.execute(airlines_table_insert, list(row))

In [90]:
airports.tail()

,Airport ID,Name,City,Country,IATA,ICAO,Altitude,Timezone,DST,Tz database time zone,Type,Source
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,272,\N,\N,\N,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,1670,\N,\N,\N,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,85,\N,\N,\N,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,670,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,0,\N,\N,\N,airport,OurAirports

In [94]:
airports.replace([r'\N'],['None'],inplace=True)

In [104]:
airports.tail(10)

,Airport ID,Name,City,Country,IATA,ICAO,Altitude,Timezone,DST,Tz database time zone,Type,Source
7688,14101,Rustaq Airport,Al Masna'ah,Oman,MNH,OORQ,349,None,None,None,airport,OurAirports
7689,14102,Laguindingan Airport,Cagayan de Oro City,Philippines,CGY,RPMY,190,None,None,None,airport,OurAirports
7690,14103,Kostomuksha Airport,Kostomuksha,Russia,None,ULPM,681,None,None,None,airport,OurAirports
7691,14104,Privolzhskiy Air Base,Astrakhan,Russia,None,XRAP,-66,None,None,None,airport,OurAirports
7692,14105,Kubinka Air Base,Kubinka,Russia,None,UUMB,614,None,None,None,airport,OurAirports
7693,14106,Rogachyovo Air Base,Belaya,Russia,None,ULDA,272,None,None,None,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,None,XIUW,1670,None,None,None,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,None,ULLK,85,None,None,None,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,670,None,None,None,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,None,UKDM,0,None,None,None,airport,OurAirports

In [107]:
airports.replace({None: np.nan})

,Airport ID,Name,City,Country,IATA,ICAO,Altitude,Timezone,DST,Tz database time zone,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,146,10,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...
7693,14106,Rogachyovo Air Base,Belaya,Russia,None,ULDA,272,None,None,None,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,None,XIUW,1670,None,None,None,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,None,ULLK,85,None,None,None,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,670,None,None,None,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,None,UKDM,0,None,None,None,airport,OurAirports

In [109]:
airports.tail(10)

,Airport ID,Name,City,Country,IATA,ICAO,Altitude,Timezone,DST,Tz database time zone,Type,Source
7688,14101,Rustaq Airport,Al Masna'ah,Oman,MNH,OORQ,349,None,None,None,airport,OurAirports
7689,14102,Laguindingan Airport,Cagayan de Oro City,Philippines,CGY,RPMY,190,None,None,None,airport,OurAirports
7690,14103,Kostomuksha Airport,Kostomuksha,Russia,None,ULPM,681,None,None,None,airport,OurAirports
7691,14104,Privolzhskiy Air Base,Astrakhan,Russia,None,XRAP,-66,None,None,None,airport,OurAirports
7692,14105,Kubinka Air Base,Kubinka,Russia,None,UUMB,614,None,None,None,airport,OurAirports
7693,14106,Rogachyovo Air Base,Belaya,Russia,None,ULDA,272,None,None,None,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,None,XIUW,1670,None,None,None,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,None,ULLK,85,None,None,None,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,670,None,None,None,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,None,UKDM,0,None,None,None,airport,OurAirports

In [159]:
airports_table_insert = ("""INSERT into airports(
Airport_ID,
Name ,	
City ,
Country ,
IATA ,	
ICAO ,	
Altitude ,	
Timezone ,	
DST ,
Tz_database_time_zone ,
Type ,
Source )
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
""")

In [163]:
for i, row in airports.iterrows():
    cur.execute(airports_table_insert, list(row))

In [169]:
airplanes_table_insert = ("""INSERT into airplanes(
Name,	
IATA_code ,	
ICAO_code)
VALUES (%s, %s, %s)
""")

In [171]:
for i, row in airplanes.iterrows():
    cur.execute(airplanes_table_insert, list(row))

In [173]:
routes_table_insert = ("""INSERT into routes(
Airline ,
Airline_ID ,
Source_airport ,	
Source_airport_ID ,
Destination_airport ,
Destination_airport_ID ,	
Stops ,	
Equipment )
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
""")

In [183]:
for i, row in routes.iterrows():
    cur.execute(routes_table_insert, list(row))

In [185]:
conn.commit()